### PR TITLE
Support dynamic import

### PR DESCRIPTION
**Pull request by oligot**
[dynamic import](https://github.com/tc39/proposal-dynamic-import) support has just landed in [Rollup 0.55.0](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#upcoming-0550).
When testing a project that uses nodent via [rollup-plugin-nodent](https://github.com/oligot/rollup-plugin-nodent), I noticed that it doesn't support dynamic import yet, resulting in the error

```
SyntaxError: Unexpected token in ...
```

Looking at the [rollup source code](https://github.com/rollup/rollup/blob/089c9e06190b894d766fc44571752fa91dc1eaa5/src/Graph.ts#L3), I see that they are using [acorn-dynamic-import](https://github.com/kesne/acorn-dynamic-import).
This pull request therefore adds the acorn-dynamic-import plugin as done in rollup itself so that the nodent compiler is able to parse code that uses dynamic import.

This is quite similar to what has been done for [buble](https://github.com/Rich-Harris/buble/pull/102).

### CODE REVIEW

**Comment by matAtWork** [comment]
That's a complicated one for me. In general, I don't like adding project specific dependancies as it means everyone now has a new bit of code, whether they need it or not (the other dependencies are required to make nodent work).

My preferred solution would be for rollup-plugin-nodent to require `acorn` and install `acorn-dynamic-import/lib/inject` before requiring `nodent` (which I believe will then require the patched version), and passing the `{ dynamicImport: true }` to nodent's options.

What do you think?

**Comment by oligot** [comment]
Ok, I'll try your proposal and see if it works...

**Comment by oligot** [comment]
And... it works 🎉 
Here is the relevant commit in rollup-plugin-nodent: https://github.com/oligot/rollup-plugin-nodent/commit/18017ade9d0d537be83edcdaeb762bdf304fe1f1

I'm going to close this one as it's no more needed.
Thanks for the suggestion !

**Comment by matAtWork** [comment]
I'm glad it worked. There is an environment/platform issue here, in that if there are multiple `acorn`s installed, or `npm` doesn't correctly dedupe, the required `acorns` will be separate and the patch won't work. This is not common, but when it goes wrong it'll be hard to debug.

A more robust method would be for me to expose a call when `acorn` is configured, so you can require/add your own acorn plugins (see parser.js:195):

lib/parser.js
```
194:            require('acorn-es7-plugin')(acorn) ;
195:            if (config.onParserInstallation) config.onParserInstallation(acorn) ;
196:            alreadyInstalledPlugin = true ;
```

...just add `onParserInstallation:function(acorn){ /* stuff here */ }` to your compilation options

For me, this is such a small change I can ship it quickly with minimal testing, and it will avoid the (rare) failure case above

**Comment by matAtWork** [comment]
`nodent-compiler@3.1.6` published to npm

https://github.com/MatAtBread/nodent-compiler/compare/93054f019902e2b107e7be681836273f35a02614...fc0ea610cfa8d43d27b0419ea29afce9d7d1c08c

**Comment by oligot** [comment]
Indeed, this is a much safer solution.
Successfully applied in https://github.com/oligot/rollup-plugin-nodent/commit/73bd769a9ef4d65144ae5876742300b503210e0e

Thanks for the quick response !

**Pull request closed without merging**
